# .github/workflows/build.yml
name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Load environment variables
        run: echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
